-- Exploratory Data Analysis
-- Database Exploration

-- Explore all objects in the Database
SELECT * FROM  INFORMATION_SCHEMA.TABLES

-- Explore all columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


-- Dimensions Exploration

-- Explore all countries our customers come from
SELECT DISTINCT country
FROM gold.dim_customers

-- Explore all categories "The major Divisions"
SELECT DISTINCT category,sub_category,product_name
FROM gold.dim_products
ORDER BY 1,2,3


-- Date Exploration

--  Find the date of the first and last order
-- How many years of sales are available
SELECT 
MIN(order_date) AS first_order_date, 
MAX(order_date) AS last_order_date,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS year_diff
FROM gold.fact_sales

-- Find the youngest and oldest customer
SELECT
(MIN(birth_date)) AS oldest_customer,
DATEDIFF(YEAR,(MIN(birth_date)), GETDATE()) AS oldest_customer_age,
(MAX(birth_date)) AS youngest_customer ,
DATEDIFF(YEAR,(MAX(birth_date)), GETDATE()) AS youngest_customer_age
FROM gold.dim_customers


--Measures Exploration

-- Find the total sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price
FROM gold.fact_sales

-- Find the total number of orders
SELECT COUNT(order_number)
FROM gold.fact_sales

SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_key) AS total_products
FROM gold.dim_products

SELECT COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_order_by_customer
FROM gold.fact_sales

-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales:' AS measure_name, 
SUM(sales_amount) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity:', SUM(quantity)
FROM gold.fact_sales
UNION ALL
SELECT 'Average Price:', AVG(price)
FROM gold.fact_sales
UNION ALL
SELECT 'Total Num. Orders:', COUNT(DISTINCT order_number)
FROM gold.fact_sales
UNION ALL
SELECT 'Total Num. Products:', COUNT(DISTINCT product_key)
FROM gold.dim_products
UNION ALL
SELECT 'Total Num. Customers:', COUNT(DISTINCT customer_key)
FROM gold.dim_customers


-- Magnitude Exploration

-- Find the total customers by countries
SELECT country, 
COUNT (customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find the total customers by gender
SELECT gender, 
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find the total products by category
SELECT category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT category, 
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated by each category?
SELECT p.category, 
SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s
	LEFT JOIN gold.dim_products p
		ON s.product_key = p.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- Find the total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) AS total_revenue_by_customer
FROM gold.fact_sales s
	LEFT JOIN gold.dim_customers c
		ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue_by_customer DESC

-- What is the distribution of sold items across countries?
SELECT country, SUM(quantity) AS total_quantity
FROM gold.fact_sales s
	LEFT JOIN gold.dim_customers c
		ON s.customer_key = c.customer_key
GROUP BY country
ORDER BY total_quantity DESC

-- Ranking Exploration

-- Which 5 products generates the highest revenue?
SELECT TOP 5 
product_name, 
SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s
	LEFT JOIN gold.dim_products p
		ON s.product_key = p.product_key
GROUP BY product_name
ORDER BY total_revenue DESC

-- What are the 5 worst performing products in terms of sales
SELECT TOP 5 
product_name, 
SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s
	LEFT JOIN gold.dim_products p
		ON s.product_key = p.product_key
GROUP BY product_name
ORDER BY total_revenue


-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_id,
c.first_name,
c.last_name,
SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key
GROUP BY 
c.customer_id,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- Find th Top 3 customers with the fewest orders placed
SELECT TOP 3
c.customer_id,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_order
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key
GROUP BY 
c.customer_id,
c.first_name,
c.last_name
ORDER BY total_order
